name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm ci
        npm run get_pdf
        npm test
        npm run build
      env:
        CI: true
        SKIP_PREFLIGHT_CHECK: true
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with: 
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build