name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        npm ci
        npm run get_pdf
        npm test -- --coverage
        npm run build
      env:
        CI: true
        SKIP_PREFLIGHT_CHECK: true
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "./coverage/lcov.info"
      